apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
data:
  grafana-config.ini: |
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [server]
    http_port = 3000
    domain = #replace with domain
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = false
    protocol = http_port

    [database]
    type = sqlite3
    host = 127.0.0.1:3306
    name = grafana
    user = {{ DATABASE_USER }}
    password = {{ DATABASE_PASSWORD }}

    [session]
    provider = file

    [analytics]
    check_for_updates = true

    [security]
    admin_user = {{ ADMIN_USER }}
    admin_password = {{ ADMIN_PASSWORD }}
    secret_key = {{ SECRET_KEY }}
    disable_gravatar = true

    [users]
    allow_sign_up = false

    [auth.anonymous]
    enabled = true

    # Kubernetes Secrets for SI
    [auth.proxy]
    enabled = true
    header_name = X-WEBAUTH-USER
    header_property = username
    auto_sign_up = true
    ldap_sync_ttl = 60

    # RBAC Config
    [auth.generic_oauth]
    enabled = true
    name = OAuth
    client_id = #replace with oauth client id
    client_secret = #replace with oauth client secret
    scopes = user:email
    auth_url = #oauth provider /auth
    token_url = #oauth provider /token
    api_url = #oauth provider /userinfo

    # Prometheus integration
    [metrics]
    enabled = true
    interval_seconds = 10
    prometheus_url = #Prometheus endpoint:9090

    # Alerting Config
    [alerting]
    enabled = true
    execute_alerts = true
    notification_email = #need demo email